name: Build Zebra

on:
  pull_request:
  push:
    branches:
      - master
      - 1.2

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Install Theos Dependencies
      run: brew install ldid fakeroot make
    
    - name: Add GNU make to PATH
      run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

    - name: Install Theos
      uses: actions/checkout@master
      with:
        repository: theos/theos
        path: theos
        submodules: recursive

    - name: Build Package
      env:
        THEOS: theos
      run: make package
